src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [   
    path('', lambda request: redirect('polls/', permanent=True)), 
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)    
]

src/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    
    path('pesquisar', views.pesquisar, name='pesquisar'),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('new', views.NewView.as_view(), name='new')
]

src/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.


class Question(models.Model):
    def __str__(self):
        return self.question_text

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def was_published_recently(self):
        now = timezone.now()        
        return now - datetime.timedelta(days=1) <= self.pub_date <= now        



class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

src/polls/forms.py
from django import forms

class PesquisaForm(forms.Form):
    texto: forms.CharField()

src/polls/views.py
from argparse import Action
from urllib import request
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from polls.forms import PesquisaForm

from polls.models import Choice, Question
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from rest_framework import viewsets
from django.views import generic
from django.utils import timezone
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    success_url = reverse_lazy('polls:index')
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def pesquisar(request):
    if (request.method == 'POST'):        
        return render(request, 'polls/index.html', {
            'texto':request.POST['texto'],
            'latest_question_list': Question.objects.filter(question_text__icontains=request.POST['texto']).order_by('-pub_date')[:5]
            })
    else:
        return render(request, 'polls/index.html', {
            'texto': None,
            'latest_question_list': Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
            })


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class NewView(generic.CreateView):
    model = Question
    fields = ['question_text', 'pub_date']
    template_name = 'polls/new.html'
    success_url = reverse_lazy('polls:index')

src/polls/templates/polls/detail.html
{% extends 'polls/model.html'%}

{% block title%}
<title>Details</title>
{% endblock %}


{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input class="btn btn-primary" type="submit" value="Vote">
</form>
{% endblock %}

src/polls/templates/polls/index.html
{% extends 'polls/model.html'%}

{% block title%}
<title>Home</title>
{% endblock %}


{% block content %}
<div class="col-md-12">
    <a type="button" class="btn btn-primary" href="{% url 'polls:new' %}">Novo</a>
</div>
<div>
    <form action="{% url 'polls:pesquisar' %}" method="post">
        {% csrf_token %}

        <div class="col-lg-6">
            <div class="input-group">
                <input type="text" class="form-control" name="texto" id="id_texto" value="{{texto}}">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
    </form>
</div>
<div class="col-md-12">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    Polls
                </th>
                <th style="width: 150px;">

                </th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for question in latest_question_list %}
            <tr>
                <td>{{ question.question_text }}</td>
                <td>
                    <a class="fa-solid fa-check-to-slot" href="{% url 'polls:detail' question.id %}"></a>
                    <a class="fa-solid fa-square-poll-horizontal" href="{% url 'polls:results' question.id %}"></a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% if not latest_question_list %}
    <p>No polls are available...</p>
    {% endif %}
</div>
{% endblock %}

src/polls/templates/polls/model.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title%}
    <title>Document</title>
    {% endblock %}

    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    {% block menu %}
    <nav class="navbar navbar-dark navbar-expand-lg shadow p-3 mb-5" style="background-color: #0c4b33;">
        <div class="container">
            <a class="navbar-brand" href="/">DJango.</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/polls">Polls</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                </ul>
            </div>
            {% if request.user.is_authenticated %}
            <div>                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Sair</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
            {% endif %}
        </div>
    </nav>
    {% endblock %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <div class="fixed-bottom" style="background-color: #44b78b; height: 80px; padding-top: 20px;">
        <div class="container">
            <div>
                <span>
                    <i class="fa-brands fa-github"></i>
                    <a href="https://github.com/edgartf3/djangoTutorial">Django Tutorial</a>
                </span>
            </div>

        </div>
    </div>
    <script type="text/javascript" src="{% static 'polls/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

src/polls/templates/polls/new.html
{% extends 'polls/model.html'%}

{% block title%}
<title>New</title>
{% endblock %}

{% block content %}
<h1>Novo cadastro</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

<!-- 
<form action="{% url 'polls:new' %}" method="post">
    {% csrf_token %}
    <div>
        <div class="col-md-12">
            <label class="form-label">Questão:</label>
            <input type="text" class="form-control" id="">
        </div>
    </div>
    <br>
    <div>
        <input class="btn btn-primary" type="submit" value="Salvar">
    </div>
    
    
</form> -->
{% endblock %}

src/polls/templates/polls/results.html
{% extends 'polls/model.html'%}

{% block title%}
<title>Result</title>
{% endblock %}


{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}